AWSTemplateFormatVersion: 2010-09-09

Description: Stack creates IAM user with permissions to assume role used by BlueChipTek for AWS review.

Parameters:
  UserName:
    Description: The name of the IAM user.
    Type: String
    Default: bct-review-user

  RoleName:
    Description: Name of IAM role that will be used for BlueChipTek for AWS review.
    Type: String
    Default: bct-review-role

Resources:
  ReviewUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref UserName
      Policies:
        - PolicyName: AssumeReviewRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              Effect: Allow
              Action: sts:AssumeRole
              Resource: !Sub 'arn:aws:iam::*:role/${RoleName}'
